on:
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: Test app
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ci
      POSTGRES_PASSWORD: ci
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      # установка зависимостей через UV
      - run: uv sync --locked --all-extras --dev

      # запуск линтера ruff
      - run: uv run ruff check . --output-format=github
      # запуск линтера typos
      - run: uv run typos .

      # билд и запуск
      - run: docker compose down -v --remove-orphans || true
      - run: docker compose build # на 2 команды т.к. долгий билд. Если объединять билд и запуск, то приложение может не успеть запуститься и тесты упадут
      - run: docker compose up -d

      # запуск тестов
      - run: uv run pytest tests --junit-xml=test-results.xml # (31.08.2025) TODO: перейти на allure в отчетах
        env:
          APP_URL: http://0.0.0.0:8000

      - run: docker compose logs app #логируем отдельно работу приложения
        if: always()

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Test results
