#on:
#  pull_request:
#    branches:
#      - main
#jobs:
#  tests:
#    name: Test app
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-python@v5
#        with:
#          python-version: '3.13'
#          cache: 'uv'

on:
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: Test app
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ci
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      APP_URL: http://0.0.0.0:8000
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - run: uv sync --locked --all-extras --dev

      - run: docker compose up -d --build

      - run: uv run pytest tests

      - run: docker compose logs app #логируем отдельно старт работу приложения
        if: always()